/**
 * mock.ts — Deterministic offline code generator.
 *
 * When no provider API key is configured (or FORCE_MOCK=1), this stands in for
 * a real LLM so the whole product — streaming, parsing, preview, versioning,
 * credits — works end-to-end with zero credentials. It emits the exact strict
 * format real providers are instructed to use, streamed in small chunks with
 * tiny delays so the SSE/typewriter experience is faithful.
 *
 * It inspects the prompt for a few keywords and produces a genuinely runnable
 * React app (a todo app, a counter, or a generic starter), with the heavily
 * commented, beginner-friendly code the product promises.
 */

import type { GenerateOptions, ModelProvider, StreamUsage } from "./provider.js";
import { estimateTokens } from "./provider.js";

function pick(prompt: string): "todo" | "counter" | "starter" {
  const p = prompt.toLowerCase();
  if (/\btodo|task|checklist|to-do\b/.test(p)) return "todo";
  if (/\bcounter|increment|click(er)?\b/.test(p)) return "counter";
  return "starter";
}

/** Build the full strict-format output string for a given prompt. */
export function buildMockOutput(prompt: string): string {
  const kind = pick(prompt);
  const title = prompt.trim().replace(/"/g, "'").slice(0, 80) || "My App";

  const pkg = `<file path="package.json">
{
  "name": "generated-app",
  "version": "1.0.0",
  "description": "Generated by AI App Builder",
  "main": "index.js",
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}
</file>`;

  const indexJs = `<file path="index.js">
// index.js
// Entry point: mounts the React <App/> into the page's #root element.
import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import "./styles.css";

// Find the container the HTML provides and render our app into it.
const container = document.getElementById("root");
const root = createRoot(container);
root.render(<App />);
</file>`;

  const styles = `<file path="styles.css">
/* styles.css — dark-first styling for the generated app. */
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
  background: #0b0f17;
  color: #e6edf3;
}
.app { max-width: 640px; margin: 0 auto; padding: 2rem 1rem; }
h1 { font-size: 1.6rem; line-height: 1.2; }
.muted { color: #8b98a9; }
button {
  background: #6d5efc; color: white; border: 0; border-radius: 8px;
  padding: 0.55rem 0.9rem; font-size: 1rem; cursor: pointer;
}
button:hover { background: #5a4ce0; }
input[type="text"] {
  width: 100%; padding: 0.6rem 0.75rem; border-radius: 8px;
  border: 1px solid #232b39; background: #121826; color: inherit; font-size: 1rem;
}
ul { list-style: none; padding: 0; }
li {
  display: flex; align-items: center; gap: 0.6rem;
  padding: 0.6rem 0.75rem; border: 1px solid #232b39;
  border-radius: 8px; margin-top: 0.5rem; background: #121826;
}
li.done span { text-decoration: line-through; color: #8b98a9; }
.row { display: flex; gap: 0.5rem; margin-top: 1rem; }
</file>`;

  let appJs = "";
  if (kind === "todo") {
    appJs = `<file path="App.js">
// App.js
// A small todo app. State lives in React and is persisted to localStorage so
// your list survives a page refresh. Every piece is commented for learners.
import React, { useState, useEffect } from "react";

// Read any previously-saved todos from the browser's localStorage on first load.
function loadTodos() {
  try {
    return JSON.parse(localStorage.getItem("todos") || "[]");
  } catch {
    return [];
  }
}

export default function App() {
  // \`todos\` is the list; \`text\` is the current value of the input box.
  const [todos, setTodos] = useState(loadTodos);
  const [text, setText] = useState("");

  // Whenever todos change, save them back to localStorage.
  useEffect(() => {
    localStorage.setItem("todos", JSON.stringify(todos));
  }, [todos]);

  // Add a new todo when the user submits the form.
  function addTodo(e) {
    e.preventDefault();
    const trimmed = text.trim();
    if (!trimmed) return; // ignore empty input
    setTodos([...todos, { id: Date.now(), text: trimmed, done: false }]);
    setText("");
  }

  // Flip a todo between done / not-done.
  function toggle(id) {
    setTodos(todos.map((t) => (t.id === id ? { ...t, done: !t.done } : t)));
  }

  // Remove a todo entirely.
  function remove(id) {
    setTodos(todos.filter((t) => t.id !== id));
  }

  return (
    <div className="app">
      <h1>${title}</h1>
      <p className="muted">A todo app with dark mode and localStorage.</p>

      <form className="row" onSubmit={addTodo}>
        <input
          type="text"
          placeholder="What needs doing?"
          value={text}
          onChange={(e) => setText(e.target.value)}
        />
        <button type="submit">Add</button>
      </form>

      <ul>
        {todos.map((t) => (
          <li key={t.id} className={t.done ? "done" : ""}>
            <input type="checkbox" checked={t.done} onChange={() => toggle(t.id)} />
            <span style={{ flex: 1 }}>{t.text}</span>
            <button onClick={() => remove(t.id)}>Delete</button>
          </li>
        ))}
      </ul>
    </div>
  );
}
</file>`;
  } else if (kind === "counter") {
    appJs = `<file path="App.js">
// App.js
// A simple counter. Demonstrates React state with useState.
import React, { useState } from "react";

export default function App() {
  // \`count\` holds the current number; \`setCount\` updates it and re-renders.
  const [count, setCount] = useState(0);

  return (
    <div className="app">
      <h1>${title}</h1>
      <p className="muted">Click the buttons to change the count.</p>
      <h2 style={{ fontSize: "3rem", margin: "1rem 0" }}>{count}</h2>
      <div className="row">
        <button onClick={() => setCount(count - 1)}>-1</button>
        <button onClick={() => setCount(count + 1)}>+1</button>
        <button onClick={() => setCount(0)}>Reset</button>
      </div>
    </div>
  );
}
</file>`;
  } else {
    appJs = `<file path="App.js">
// App.js
// A generic starter screen. It echoes your prompt and gives you a place to
// start building. Edit this file in the Monaco editor and watch the preview.
import React, { useState } from "react";

export default function App() {
  const [clicks, setClicks] = useState(0);
  return (
    <div className="app">
      <h1>${title}</h1>
      <p className="muted">
        Your app scaffold is ready. This starter was generated from your prompt.
        Edit <code>App.js</code> to make it your own.
      </p>
      <div className="row">
        <button onClick={() => setClicks(clicks + 1)}>
          Clicked {clicks} time{clicks === 1 ? "" : "s"}
        </button>
      </div>
    </div>
  );
}
</file>`;
  }

  const readme = `<file path="README.md">
# ${title}

Generated by **AI App Builder**.

## Run locally

\`\`\`bash
npm install
npm start
\`\`\`

Then open the URL the dev server prints. This project previews live in the
in-app Sandpack sandbox — no setup required there.
</file>`;

  return [
    `<meta template="react" entry="App.js" />`,
    pkg,
    indexJs,
    styles,
    appJs,
    readme,
  ].join("\n");
}

export class MockProvider implements ModelProvider {
  async *stream(opts: GenerateOptions): AsyncGenerator<string, StreamUsage, void> {
    const output = buildMockOutput(extractPrompt(opts.userMessage));
    // Stream in small chunks to emulate token-by-token delivery.
    const chunkSize = 24;
    for (let i = 0; i < output.length; i += chunkSize) {
      if (opts.signal?.aborted) break;
      yield output.slice(i, i + chunkSize);
      // Small delay so the typewriter effect is visible but generation is quick.
      await sleep(8);
    }
    return {
      inputTokens: estimateTokens(opts.system + opts.userMessage),
      outputTokens: estimateTokens(output),
      providerCacheHit: false,
      engine: "mock",
    };
  }
}

/** Pull the human request back out of the built user message. */
function extractPrompt(userMessage: string): string {
  const m = userMessage.match(/REQUEST:\s*([\s\S]*)$/) || userMessage.match(/^Build this:\s*([\s\S]*)$/);
  return (m?.[1] ?? userMessage).trim();
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}
